### ISSUE TITLE
Crush with H&C

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [0999312/CoffeeWorkshop#13]
还联动呢。
自己装什么都没问题，装了热量与气候直接崩_(:з」∠)_
崩溃报告：
[crash-2020-05-10_11.11.51-client.txt](https://github.com/0999312/CoffeeWorkshop/files/4605077/crash-2020-05-10_11.11.51-client.txt)

**Comment by WuzgXY-GitHub** [comment]
只装H&C Lib似乎没什么问题？

**Comment by 0999312** [comment]
咖啡工坊重置中，不接受BUG反馈

**Comment by gatoborrachon** [comment]
sorry, but what means Mod Resetting? this issue will be fixed or you will abandon 1.12? there were not updates in almost 2 years

抱歉，但是Mod重置是什么意思？ 这个问题将会解决，还是您放弃1.12？近两年没有更新
