### ISSUE TITLE
[Suggestion] Config option to disable or increase or decrease sodium ore spawn

### ISSUE THREAD

**Issue by DWX12** [0999312/CoffeeWorkshop#3]
Would really like to see a config option to be able to control the spawn of the sodium ore.

This mod has alot of wonderful content and hope you will continue to expand on it.

Thank you.

**Comment by 0999312** [comment]
🤔 OK

**Comment by DWX12** [comment]
Ideally an option to just disable the spawning of the ore entirely. Working on a modpack right now and that's the only ore I cannot control. Hoping to see this option in a future update.

By the way, great work. This mod really is rather neat. I'm using it along side mods such as Growthcraft, Pizzacraft, CoffeeSpawner, TeaStory, and many others and it fits rather well.
